// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtNZO9dfLEKUl7agnc_6jLuUVNKEIucY',
    appId: '1:649055118946:web:04b845136d3bf9d34a533b',
    messagingSenderId: '649055118946',
    projectId: 'pharmacy-system-depi',
    authDomain: 'pharmacy-system-depi.firebaseapp.com',
    storageBucket: 'pharmacy-system-depi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1wDjsKSm6jIgE2Bt5jY9IqGlADsAd5o',
    appId: '1:649055118946:android:4df20834dde28aae4a533b',
    messagingSenderId: '649055118946',
    projectId: 'pharmacy-system-depi',
    storageBucket: 'pharmacy-system-depi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-iBYwNfnlR5wIwpiAn0aImAOAstrJus',
    appId: '1:649055118946:ios:0694dcc045010d3a4a533b',
    messagingSenderId: '649055118946',
    projectId: 'pharmacy-system-depi',
    storageBucket: 'pharmacy-system-depi.firebasestorage.app',
    iosBundleId: 'com.example.pharmacySystem',
  );
}
